### ISSUE TITLE
Data/Clock Labels for PDM Mic are switched on the board and schematic

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_E_Hardware#11]
Please refer to Tympan Rev-D issue and confirm that this applies to the Rev-E as well: https://github.com/Tympan/Tympan_Rev_D_Hardware/issues/5

**Comment by biomurph** [comment]
Confirmed that this issue did persist from Rev D to Rev E.
Made the changes and pushed to fix this issue.
