### ISSUE TITLE
Room for QUIIC?

### ISSUE THREAD

**Issue by chipaudette** [Tympan/Tympan_Rev_E_Hardware#14]
@biomurph There's no room for a QUIIC connector anywhere is there?  (I do love QUIIC)

**Comment by biomurph** [comment]
It looks like a Qiic connector could fit under the volume knob... lousy location...
Mayby I could throw one in above MIC1 next to the speaker jack?

**Comment by biomurph** [comment]
Here's a shot of the Qwiic location that is the easiest to do.
It's at the front of the board, on the bottom layer, underneath the PROGRAM pushbutton between the audio jacks.

<img width="1097" alt="qwiic conn rev E" src="https://user-images.githubusercontent.com/6284057/118839635-a6eaac00-b894-11eb-8a77-e84c223b6f11.png">

**Comment by biomurph** [comment]
Placec Qwiic connector on the bottom near the battery connector. It fits!

<img width="720" alt="Qwiic Conn" src="https://user-images.githubusercontent.com/6284057/119173742-a9d0d280-ba35-11eb-81b5-47543eda7618.png">
