### ISSUE TITLE
Select Battery 

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_E_Hardware#17]

**Comment by biomurph** [comment]
The teensy is about 60mm (2.4") long 
Tympan E is 74mm (2.9") long
Tympan E is 38mm (1.5") wide
Updated Dimensions in PCB file

[Candidate 1](https://www.adafruit.com/product/258) is 1200mAh, 62mm long x 34mm x 5mm

[Candidate 2](https://www.amazon.com/Part-Number-Rechargeable-1200mAh-Connector/dp/B091FFPFB1/ref=zg_bs_10112773011_33?_encoding=UTF8&refRID=7R5REXV7YG7WFS9SC7NT&th=1) is 1200mAh, 40mm long x 30mm wide x 10mm thick

[Candidate 3](https://www.amazon.com/2000mAh-Rechargable-Protection-Insulated-Development/dp/B08T6QS58J/ref=sr_1_10?dchild=1&keywords=Lipo+battery&qid=1623330697&refinements=p_36%3A1253560011%2Cp_n_feature_two_browse-bin%3A389568011%7C389571011&rnid=389545011&s=toys-and-games&sr=1-10) is 2000mAh, 50mm long x 33mm wide x 10mm thick

[Candidate 4](https://www.amazon.com/YDL-1700mAh-battery-Rechargeable-Connector/dp/B07BTRTR9R/ref=sr_1_13_sspa?dchild=1&keywords=Lipo+battery&qid=1623330697&refinements=p_36%3A1253560011%2Cp_n_feature_two_browse-bin%3A389568011%7C389571011&rnid=389545011&s=toys-and-games&sr=1-13-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExVlA3S0ZXUlZJRzhIJmVuY3J5cHRlZElkPUEwMDA3NzAyMTFIREtGRFNZSU8xVCZlbmNyeXB0ZWRBZElkPUEwNzExOTQ5MzQ0U0Q2UTNHRzBPMCZ3aWRnZXROYW1lPXNwX210ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=) is 1700mAh, 52 x 28 x 10mm

@eyuan-creare I think I'm seeing a battery here that will fit to allow access to the SD card and also have enough power capacity. What do you think?

**Comment by biomurph** [comment]
As per your email design idea, if you want to put a cylinder battery along side, would this work?

[Candidate 5](https://www.adafruit.com/product/1781) 2200mAh 69mm x 18mm

**Comment by eyuan-creare** [comment]
Notes from @chipaudette: 

The 500 mA-hr batteries really aren’t going to cut it for RevE.  They were marginal for RevD; we saw lots of brown-out behavior much earlier than I would have expected.  

We’re clearly not getting as much of the battery capacity as we’d like.  I think that it’s because the regulator has more of a drop-out (at our current load) than we’d really like.  So, the battery can’t be pulled as low in voltage as its capacity rating expects.

Some current draw measurements are after my signature.  In my experience, the RevD would start to brown out (dropped BT connections is the first symptom) as we started to get towards two hours…shorter if writing to the SD card.  The RevE will be worse.

In my opinion, 500 mA-hr is too small for RevE.

Data, January 2021

Tympan RevD: Power draw seems to be 160 mA
•	2-channel, 96 kHz sample rate
•	BT is on but not connected to anything
•	SD card inserted but not being used
•	Frequency-domain audio processing load of 78% of CPU

Tympan RevE: Power draw seems to be 178 mA
•	2-channel, 96 kHz sample rate
•	BT is on but not connected to anything
•	SD card inserted but not being used
•	Same Freq-domain audio processing, but the faster CPU results in only 11% usage

**Comment by eyuan-creare** [comment]
@biomurph To ship lithium batteries, they need to be tested to UN38.3.  Otherwise they must be shipped hazardous material (class-9) which has a hefty fee.  

There are a few battery places overseas that can perform this test cheaply such as sz-battery.
- 20 business days for attaching leads then testing.
- $500 testing + 10cells + 10 batteries to be destroyed

For cost, 2-3AHr Li-poly batteries were around $5/ea in quantities of 10 to 25 pcs.'

Lead time is long, and we would need to verify the testing is legit.'

**Comment by biomurph** [comment]
@eyuan-creare that may be more than we can realistically pull off in the near term. I would like to use one of the batteries listed. I don't have a problem with shipping via UPS or other. When I do, it does not go on a plane or it goes on a special plane.

I think the testing is overkill. Is this something that Create has specified?

**Comment by eyuan-creare** [comment]
No, it is mandated by the Federal Transportation Code ([49 CFR § 172 C-H](https://www.ecfr.gov/cgi-bin/text-idx?SID=6b16517c141a916e66bb34dbfcfc17fa&mc=true&node=se49.2.173_1185&rgn=div8)) and covers all US ground and air shipments.  Additionally, UPS and FedEx states similar rules, which is why they ask if a shipment has lithium batteries in it.

- [FAA Guide on Shipping Lithium Batteries](https://www.faa.gov/hazmat/safecargo/media/Battery_Slides.pdf)
- [ITAA Battery Guidance](https://www.iata.org/contentassets/05e6d8742b0047259bf3a700bc9d42b9/lithium-battery-guidance-document-2020.pdf)
- [FedEx Air Shipping Guide](http://ftn.fedex.com/us/assets/docs/Lithium-Battery-Shipping-Tool_CY19.pdf?cmp=AFC-999999-1-1-0-0000010-US-EN-WEBUSLITHBATTR1)
-  [UPS Shipping Batteries Guideline](https://www.ups.com/assets/resources/media/en_US/pack_ship_batteries.pdf)

From UPS:

![image](https://user-images.githubusercontent.com/42774675/121584589-9fd03d00-c9ff-11eb-88e6-189cf68a150d.png)

**Comment by biomurph** [comment]
I'm asking if candidate 4 is tested to the spec.
I always just assumed that if they were shipped to me, they are OK. Also, they do have overcurrent protection on them.

I do follow the guide when I do shipping with UPS, for example, There is a way to check a box and tell them there is lithium battery enclosed inside product. I never have a problem at all.

**Comment by eyuan-creare** [comment]
Perhaps there are more stringent rules depending on the definition of a distributor, rather than a private individual.

**Comment by biomurph** [comment]
could be. I am very comfortable shipping under my account any of the batteries that are listed.

In looking for the spec test, I realize that Candidate 3 is not an option because it uses a smaller JST (1.25mm, not 2mm pitch).

**Comment by eyuan-creare** [comment]
Sweet! I tracked down the UN38.3 test report for Adafruit's 2000mAh battery: 
[LP803860_UN38-3.pdf](https://github.com/Tympan/Tympan_Rev_E_Hardware/files/6665854/LP803860_UN38-3.pdf)

If we wanted to order in bulk (and didn't mind long lead times) we could order straight from [PKCell](http://www.batterypkcell.com/un38-3-certificate/):

**Comment by biomurph** [comment]
Ok! We will use that size for this build. 
I'll look at the lead times. Might be OK to get a small amount right away and wait for the rest

**Comment by eyuan-creare** [comment]
I'm open to what battery we use, but that 2000mAh fits so nicely.  If we want to leave extra room let me know by Thurs morning as I am beginning to shape the case.

![image](https://user-images.githubusercontent.com/42774675/122321849-88f38400-cef2-11eb-955c-87a82ab4bd15.png)

**Comment by biomurph** [comment]
Let's stick with the Adafruit 2000mAh battery.
Also, please check the lead length of the battery connector. You might need to flip the battery around so the cable is at the USB end?

This might not be an issue, but worth seeing that everything fits right.

**Comment by eyuan-creare** [comment]
Sounds good.  The battery lead is 4.25in so it should work either direction.

**Comment by eyuan-creare** [comment]
Closing this out.  I'll design around the Adafruit 2000mAh li-poly, unless it can't fit.
