### ISSUE TITLE
June 2021 Production AIC Shield Quad Pass Thru

### ISSUE THREAD

**Issue by biomurph** [Tympan/Tympan_Rev_E_Hardware#22]
The Quad Pass Through sketch from the examples is not working.
I'm getting a pile of I2C errors. I believe that this is not functional yet?

Library branch: feature_Tympan4_SD_ble
Teensyduino beta9, Arduino 1.8.15

**Comment by chipaudette** [comment]
Did you change **both** lines to enable RevE?

```
Tympan                        myTympan(TympanRev::E);    //note: Rev C is not compatible with the AIC shield
AICShield                     aicShield(TympanRev::E, AICShieldRev::A);   //note: Rev C is not compatible with the AIC shield
```

**Comment by biomurph** [comment]
That fixed it!
AudioPassThruQuad Test Passed!
