### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by justinclift** [Tympan/Tympan_Rev_E_Hardware#8]
Noticed a cut-n-paste typo in the project description, and figured it's probably useful to mention:

```
Repository for Tympan Rev D Electronics and case designs 
```

"Rev D" → "Rev E"

:wink:

**Comment by chipaudette** [comment]
Looks like it's been fixed!  Thanks!

**Comment by justinclift** [comment]
Looking at the project description again just now... er... it's still saying "Rev D"?

![tympan_temp1](https://user-images.githubusercontent.com/406299/94320855-5d7de180-ffd1-11ea-9130-753b34aa53e0.png)
