### ISSUE TITLE
Bring Teensy reset button up to the Tympan 

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_E_Hardware#9]
In the existing enclosure, the battery obscures the reset button.  If we brought the reset signal up to the Tympan, then we could place a second reset button in a better location.  Likely, this would be a "side-press" button, but that is TBD.

- Existing enclosure:

<img src="https://user-images.githubusercontent.com/42774675/104026823-7d0dd400-5194-11eb-9b7f-1fa7d6e8fabf.png" height =200/>

- Teensy 4.1 Schematic showing the PROGO trace from the reset button:
<img src="https://user-images.githubusercontent.com/42774675/104027005-c65e2380-5194-11eb-9a39-7796b021e212.png" height =200/>

- Teensy 4.1 PCB showing the trace from the PROGO pin to the Reset Button.  @chipaudette confirmed that this thru hole pin transitions LOW when the reset button is pressed

<img src="https://user-images.githubusercontent.com/42774675/104027094-ea216980-5194-11eb-9564-20927758d0de.png" height =200/>

**Comment by eyuan-creare** [comment]
@biomurph looked into where the pin would fall:

Here is about the location of the pad that we would need to place for it.
![image](https://user-images.githubusercontent.com/42774675/104027329-3ec4e480-5195-11eb-8bdd-c688aa2b3687.png)

 

The good news is that the pad for the pin next to it (pin 30) is not in the way.
Also, there's enough room to either place a thru-hole, with a bunch of parts/trace juggling, or placement of a single SMT pad, with less parts/trace juggling.

There's also the option of flying a lead from the T 4.1 to the Tympan..

**Comment by eyuan-creare** [comment]
@biomurph suggested placing a momentary pushbutton (TL6340AF160Q) between the audio jacks:

<img src="https://user-images.githubusercontent.com/42774675/118533441-14bc9980-b716-11eb-8d74-6b369253ae00.png" height =100/>

This should work fine, though it is a tiny switch.  The button is 1/32" tall. @chipaudette if you fine using a paper clip, I can put a guide hole in.  If you would like a feature on the case with a cantilevered tab, then we should go bigger.

**Comment by biomurph** [comment]
possible candidate switches
https://www.mouser.com/datasheet/2/910/909_2894_2893_DTSA-6-1571568.pdf
The DTSA-6 drawing will fit and it is a decent size. There are tons of them.

**Comment by eyuan-creare** [comment]
Goldilocks says... that switch is just too big!  It does fit, within the height of the stock headers but let me see it there is an alternative.

![image](https://user-images.githubusercontent.com/42774675/118555294-83a6ec00-b730-11eb-8137-7ffa9f61f93e.png)

**Comment by eyuan-creare** [comment]
@biomurph What do you think of this switch? (faked up CAD model).  It still feels a bit big but there is not much out there for RA switches. 
- APEM MJTP1117 ($.48 [Digikey](https://www.digikey.com/en/products/detail/apem-inc/MJTP1117/1795496)) SPST- NO
<br>
<img src="https://user-images.githubusercontent.com/42774675/118558663-f74af800-b734-11eb-85cf-5e6a5672c4f6.png" height=200/>
<br>
<img src="https://user-images.githubusercontent.com/42774675/118558849-34af8580-b735-11eb-9f22-ee0531527d0a.png" height=200/>
<br>
<img src="https://user-images.githubusercontent.com/42774675/118559091-76d8c700-b735-11eb-9180-79d28045925e.png" height=200/>
<br>
I'll cut a hole in the case so that the switch is set back from the outside. See the thin blue box below.
<img src="https://user-images.githubusercontent.com/42774675/118559636-3b8ac800-b736-11eb-8e29-bd3c188aa99a.png" height=200/>

**Comment by biomurph** [comment]
Works great! Im down to use it. 
You have it overhanging the edge of the PCB. Is that how you want to?

**Comment by eyuan-creare** [comment]
@biomurph yes, please have the button overhang. Thanks!

**Comment by biomurph** [comment]
I placed the MJTP-117 push button between the audio jacks

**Comment by chipaudette** [comment]
@eyuan-creare , is this done?  can we close this?
